# Generated by Django 4.2.7 on 2025-06-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_api', '0002_nlpmodel_notificationchannel_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpmodel',
            name='is_trained',
            field=models.BooleanField(default=False, verbose_name='Entraîné'),
        ),
        migrations.AddField(
            model_name='nlpmodel',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation'),
        ),
        migrations.AddField(
            model_name='nlpmodel',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'utilisations"),
        ),
    ]
