# Generated by Django 4.2.7 on 2025-06-01 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback_api', '0003_nlpmodel_is_trained_nlpmodel_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlptrainingdata',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='nlptrainingdata',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_training_data', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
