# Generated by Django 4.2.7 on 2025-06-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_api', '0004_nlptrainingdata_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordrule',
            name='name',
            field=models.CharField(default='Règle sans nom', max_length=100, verbose_name='Nom'),
        ),
    ]
